create table author(
  id            uuid   not null     primary key,
  name          text   not null,
  surname       text   not null
);

create table book(
  id            uuid                      not null        primary key,
  name          text                      not null        unique,
  author        uuid                      not null        references author(id),
  created_at    timestamp with time zone  not null,
  modified_at   timestamp with time zone
);

create table author_audit(
  id            int     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id     uuid         not null,
  created_by    text                        not null,
  created_at    timestamp    not null DEFAULT now(),
  data          jsonb
);
